---
title: "EDA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(pracma)

data %>%
  keep(is.numeric) %>% 
  select(-X1) %>%
  gather() %>% 
  ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_histogram() +
    ggtitle("Distributions of Continuous Predictor Variables")

data %>%
  keep(is.factor) %>% 
  select(-album, -title) %>%
  gather() %>% 
  ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_bar() +
    ggtitle("Distributions of Categorical Predictor Variables")
```

```{r}

dontgraph = c('X1','popularity','id','album','type','title')

for (i in colnames(data))
{
  if (i %in% dontgraph)
  {
  }
  else if (!is.numeric(data[[i]]))
  {
    print(ggplot(data,aes(data[[i]],popularity))+
      geom_boxplot()+
      labs(x=i,y="Popularity",title=paste("Popularity vs.",i)))
  }
  else 
  {
    print(ggplot(data,aes(data[[i]],popularity))+
      geom_point()+
      labs(x=i,y="Popularity",title=paste("Popularity vs.",i)))
  }
}
```

